### ISSUE TITLE
Crashes when playing AV1 video

### ISSUE THREAD

**Issue by ardivee** [jakky1/video_player_win#1]
When trying to play a video with the AV1 codec it crashes the app, it is working fine with Windows Media player.

I have installed the AV1 codec from the Microsoft Store, before that it would just not play the video.

**Comment by jakky1** [comment]
I pushed a solution to github, it can solve this issue.

However this solution didn't handle the odd video width/height, 
so I will handle it in these two days, and then will push to pub.dev

If you need the temp solution ASAP, please try the newest version on github:

```
dependencies:
  video_player: ^2.4.7
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: master
```
	  
	  
By the way, 
I can't find the way to play AV1 video with K-lite codec, (even though it can be played by Windows Media Player...)
but this solution can play AV1 with "AV1 video extention" in Microsoft Store you mentioned.
I will add this information into README later.
