### ISSUE TITLE
[Support Request] Do we have plans to implement the ability to load videos from assets?

### ISSUE THREAD

**Issue by yubnxd** [jakky1/video_player_win#18]

**Comment by jakky1** [comment]
There is no plan to implement it.

I have no idea how to read flutter asset file in C++,
and have no idea how to pass a byte stream to Windows Media Foundation.

**Comment by yubnxd** [comment]
> There is no plan to implement it.
> 
> I have no idea how to read flutter asset file in C++, and have no idea how to pass a byte stream to Windows Media Foundation.

Thanks for the explanation

**Comment by jakky1** [comment]
@ncdm-stldr ,
Thanks for the hint.
It make things easier.

I implement it and push to github.
Please use the following dependency,
and let me know if it works for you.
```yaml
dependencies:
  video_player_win:
    git:
      url: https://github.com/jakky1/video_player_win.git
      ref: master
```
