### ISSUE TITLE
httpHeaders are not set correctly

### ISSUE THREAD

**Issue by Bonfra04** [jakky1/video_player_win#45]
The `VideoPlayerController.network` constructor accepts an `httpHeaders` paramether; Setting, for example, the `User-Agent` to something specific is not reflected in the HTTP request made by the controller.

As an example, invoking the constructor like this:
```dart
VideoPlayerController.networkUrl(uri,
    httpHeaders: {"User-Agent": "FOOBAR"}
);
```
results anyway in an HTTP call with User-Agent set to `NSPlayer/12.00.19041.5007 WMFSDK/12.00.19041.5007`

**Comment by jakky1** [comment]
I tried to support http headers.
Because currently I am not sure whether it can work normally,
so I implement it in a new branch on github.

Please try it with the following dependency:
```yaml
 dependencies:   
     video_player_win:
       git:
         url: https://github.com/jakky1/video_player_win.git
         ref: support_http_headers
```

If http headers not set, the package works in the same way as before.
If http headers set, it works in a new way.

Known issues:
1. If http headers set, .m3u8 url cannot be played.
2. If http headers set, can network video be played normally every time ??  ( HELP ! test WANTED )
3. If http headers set, can network video be played behind http proxy ??  ( HELP ! test WANTED )

Please let me know if it works well :)
